//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 10.3.2017. 12:32:20
namespace Mad_Head_Puzzle
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Audio
            {
                
                /// <summary> Path to Content/Assets/Audio/background.mp3 </summary>
                public const string background_mp3 = "Content/Assets/Audio/background.mp3";
                
                /// <summary> Path to Content/Assets/Audio/congratulations.wav </summary>
                public const string congratulations_wav = "Content/Assets/Audio/congratulations.wav";
            }
            
            public sealed class Images
            {
                
                /// <summary> Path to Content/Assets/Images/background.png </summary>
                public const string background_png = "Content/Assets/Images/background.png";
                
                /// <summary> Path to Content/Assets/Images/congratulations.png </summary>
                public const string congratulations_png = "Content/Assets/Images/congratulations.png";
                
                /// <summary> Path to Content/Assets/Images/gamelogo.png </summary>
                public const string gamelogo_png = "Content/Assets/Images/gamelogo.png";
                
                /// <summary> Path to Content/Assets/Images/instructions.png </summary>
                public const string instructions_png = "Content/Assets/Images/instructions.png";
                
                /// <summary> Path to Content/Assets/Images/intro.png </summary>
                public const string intro_png = "Content/Assets/Images/intro.png";
                
                /// <summary> Path to Content/Assets/Images/piece0.png </summary>
                public const string piece0_png = "Content/Assets/Images/piece0.png";
                
                /// <summary> Path to Content/Assets/Images/piece1.png </summary>
                public const string piece1_png = "Content/Assets/Images/piece1.png";
                
                /// <summary> Path to Content/Assets/Images/piece2.png </summary>
                public const string piece2_png = "Content/Assets/Images/piece2.png";
                
                /// <summary> Path to Content/Assets/Images/piece3.png </summary>
                public const string piece3_png = "Content/Assets/Images/piece3.png";
                
                /// <summary> Path to Content/Assets/Images/piece4.png </summary>
                public const string piece4_png = "Content/Assets/Images/piece4.png";
                
                /// <summary> Path to Content/Assets/Images/piece5.png </summary>
                public const string piece5_png = "Content/Assets/Images/piece5.png";
                
                /// <summary> Path to Content/Assets/Images/piece6.png </summary>
                public const string piece6_png = "Content/Assets/Images/piece6.png";
                
                /// <summary> Path to Content/Assets/Images/piece7.png </summary>
                public const string piece7_png = "Content/Assets/Images/piece7.png";
                
                /// <summary> Path to Content/Assets/Images/resetbutton.png </summary>
                public const string resetbutton_png = "Content/Assets/Images/resetbutton.png";
                
                /// <summary> Path to Content/Assets/Images/slot.png </summary>
                public const string slot_png = "Content/Assets/Images/slot.png";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
